=== TechSysApi/cen-mc-rc-dist/v3.0.0/model/json-schema-v4-full/submit-mailpiece.json
{
  "type": "object",
  "properties": {
    "mailpieceId": {
      "type": "string",
      "description": "The mailpieceId represents the machine specific identifier to track a mail item during a machine sorting cycle. The identifier is used to synchronize the data events between coding and sorting systems.",
      "maxLength": 200
    },
    "idTag": {
      "type": "string",
      "description": "Represents a long living identifier for the mail item\r\n[DEPRECATED] Is replaced by the attribute idTags. Attribute will be removed in future releases when all target systems use the new field idTags.",
      "maxLength": 200
    },
    "timestamp": {
      "type": "string",
      "description": "Timestamp of data collection.",
      "format": "date-time"
    },
    "sourceId": {
      "type": "string",
      "description": "Refers to a module id as event-source.",
      "pattern": "[A-Z]{3}[0-9]{2}"
    },
    "mpAttr": {
      "$ref": "#/definitions/MailpieceAttr",
      "description": "The MailpieceAttrT type is assigned to the element mp_attr. It provides basic\r\nmailpiece related information:\r\n\r\n- the kind of the mail item\r\n- the mailclass of the mail item; important for the ED because it and may affect the address recognition\r\n- the scanned faces of the mail item. The FaceSetT type is assigned to faces and allows providing a sequence of faces.\r\n   The FaceSetT types allows to link a face with the corresponding image by a page attribute.\r\n- a preknowledge result if a barcode reader or some other type of Enrichment Device is directly attached to the MC.\r\n   This result will be in accordance with the result type specified in the IC-ED interface."
    }
  },
  "required": [
    "mailpieceId",
    "timestamp",
    "sourceId"
  ],
  "additionalProperties": false,
  "id": "SubmitMailpiece",
  "$schema": "http://json-schema.org/draft-04/schema#",
  "definitions": {
    "MailpieceAttr": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/MailpieceType",
          "description": "Defines the type of the mail item."
        },
        "preknowledge": {
          "$ref": "#/definitions/RecognitionResult",
          "description": "Provides preknowledge to the RC System, e.g. a barcode\r\nresult if a barcode reader is integrated into the machine."
        }
      },
      "required": [
        "type"
      ],
      "additionalProperties": false,
      "description": "This type is taken from CEN/TS 15448 and extended by a “preknowledge” element.\r\nThe type MailpieceAttrT specifies basic mailpiece attributes.",
      "$id": "MailpieceAttr"
    },
    "MailpieceType": {
      "type": "string",
      "enum": [
        "UNKNOWN",
        "LETTER",
        "LETTER_BUNDLE",
        "FLAT",
        "FLAT_BUNDLE",
        "PARCEL"
      ],
      "$id": "MailpieceType"
    },
    "RecognitionResult": {
      "type": "object",
      "properties": {
        "barCodes": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/BarCode"
          },
          "description": "Contains all barcodes/matrix codes identified by the reading system.\r\n\r\nThe reading system should read and send all available barcodes/matrix codes. The consuming systems will apply further classification and filtering."
        },
        "location": {
          "$ref": "#/definitions/Location"
        },
        "dimension": {
          "$ref": "#/definitions/Dimension",
          "description": "dimension of the mail piece."
        },
        "weight": {
          "$ref": "#/definitions/Weight",
          "description": "weight of the mail piece."
        },
        "legalForTrade": {
          "$ref": "#/definitions/LegalForTrade",
          "description": "Legal For Trade information."
        },
        "binOccupancy": {
          "$ref": "#/definitions/BinOccupancyState"
        }
      },
      "additionalProperties": false,
      "$id": "RecognitionResult"
    },
    "BarCode": {
      "type": "object",
      "properties": {
        "type": {
          "$ref": "#/definitions/BarCodeSymbology",
          "description": "Provides the valid symbologies of a barcode label."
        },
        "value": {
          "type": "string",
          "description": "This element contains the value of the barcode."
        },
        "status": {
          "$ref": "#/definitions/BarCodeStatus",
          "description": "[DEPRECATED] Replaced by BarcodeSymbology.NOT_RECOGNIZED. Field will be removed in future release."
        }
      },
      "required": [
        "status"
      ],
      "additionalProperties": false,
      "description": "This type contains a barcode.",
      "$id": "BarCode"
    },
    "BarCodeSymbology": {
      "type": "string",
      "enum": [
        "NOT_RECOGNIZED",
        "CODE_128",
        "DATA_MATRIX",
        "CODE_39",
        "I2OF5",
        "QR"
      ],
      "description": "Provides the valid symbologies of a barcode label",
      "$id": "BarCodeSymbology"
    },
    "BarCodeStatus": {
      "type": "string",
      "enum": [
        "NO_BARCODE",
        "DETECTED_AND_RECOGNIZED",
        "DETECTED_AND_NOT_RECOGNIZED"
      ],
      "description": "The result status of the barcode recognition.\r\nDETECTED_AND_RECOGNIZED if the barCode symbology is recognized.\r\nDETECTED_AND_NOT_RECOGNIZED if the barCode symbology is not recognized.",
      "$id": "BarCodeStatus"
    },
    "Location": {
      "type": "object",
      "properties": {
        "face": {
          "$ref": "#/definitions/MailpieceFace",
          "description": "# GER-TODO\r\nZur Erkennung auf welcher Seite (welche Kamera) der Identcode gelesen wurde (z.B. für VCS…).\r\nDer Wert ist nur auf den Identcode (national) bezogen."
        },
        "polygon": {
          "$ref": "#/definitions/Polygon",
          "description": "Achtung: Die Punkte in Förderrichtung durchnummeriert, im Unterschied zum CEN-Standard, wo sie im (Gegen-)Uhrzeigersinn ausgerichtet sind.\r\nDie Punkte werden wie folgt ermittelt/ausgegeben:\r\nerster Punkt in Förde-richtung ist der Start-punkt gezählt wird fortlaufend in Förderichtung (nicht Uhrzeigersinn)\r\nalle Angaben sind bezogen auf den Triggernullpunkt (= Schalenanfang) ‚x’ wird in Förderrichtung ermittelt; ‚y’ quer zur Förderrichtung"
        }
      },
      "additionalProperties": false,
      "description": "To specify a region location, the region descriptor LocationT listed subsequently is used. LocationT encloses\r\nno information about the image orientation. The image orientation is specified in the TIFF header. Region\r\ncoordinates are given in pixel and are related to the image origin which corresponds to the upper left corner.\r\nThe coordinates are independent of the TIFF orientation.",
      "$id": "Location"
    },
    "MailpieceFace": {
      "type": "string",
      "enum": [
        "TOP",
        "LEFT",
        "RIGHT",
        "FRONT",
        "REAR",
        "BOTTOM",
        "FRONT_LEFT",
        "FRONT_RIGHT",
        "REAR_LEFT",
        "REAR_RIGHT"
      ],
      "$id": "MailpieceFace"
    },
    "Polygon": {
      "type": "object",
      "properties": {
        "dot": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/PolygonDot"
          }
        }
      },
      "required": [
        "dot"
      ],
      "additionalProperties": false,
      "$id": "Polygon"
    },
    "PolygonDot": {
      "type": "object",
      "properties": {
        "x": {
          "type": "number"
        },
        "y": {
          "type": "number"
        }
      },
      "required": [
        "x",
        "y"
      ],
      "additionalProperties": false,
      "$id": "PolygonDot"
    },
    "Dimension": {
      "type": "object",
      "properties": {
        "length": {
          "type": "integer",
          "description": "Length in [mm]."
        },
        "width": {
          "type": "integer",
          "description": "Width in [mm]."
        },
        "height": {
          "type": "integer",
          "description": "Height in [mm]."
        },
        "state": {
          "$ref": "#/definitions/DimensionMeasurementState"
        }
      },
      "additionalProperties": false,
      "description": "Dimension measurement of the mail piece",
      "$id": "Dimension"
    },
    "DimensionMeasurementState": {
      "type": "object",
      "properties": {
        "measurementResult": {
          "$ref": "#/definitions/DimensionMeasurementResultType"
        },
        "measurementRange": {
          "$ref": "#/definitions/DimensionMeasurementRangeType"
        },
        "itemSizeClassification": {
          "$ref": "#/definitions/ItemSizeClassificationType"
        }
      },
      "required": [
        "measurementResult",
        "measurementRange",
        "itemSizeClassification"
      ],
      "additionalProperties": false,
      "description": "State of the measurement.",
      "$id": "DimensionMeasurementState"
    },
    "DimensionMeasurementResultType": {
      "type": "string",
      "enum": [
        "OK",
        "NOK",
        "NOT_RECOGNIZED"
      ],
      "description": "Measurement result state.\r\n\r\n- OK: Measurement VMS ok\r\n- NOK: Measurement VMS not ok\r\n- NOT_RECOGNIZED: No object recognized",
      "$id": "DimensionMeasurementResultType"
    },
    "DimensionMeasurementRangeType": {
      "type": "string",
      "enum": [
        "INSIDE",
        "OUTSIDE"
      ],
      "description": "- INSIDE: Object is within the measurement range\r\n- OUTSIDE: Object is outside of the measurement range",
      "$id": "DimensionMeasurementRangeType"
    },
    "ItemSizeClassificationType": {
      "type": "object",
      "properties": {
        "ok": {
          "type": "boolean",
          "description": "True: object size ok\r\nFalse: Object size not ok (over and/or undersized, see corresponding flags)"
        },
        "oversized": {
          "type": "boolean",
          "description": "object too big to be measured"
        },
        "undersized": {
          "type": "boolean",
          "description": "object too small to be measured"
        }
      },
      "required": [
        "ok",
        "oversized",
        "undersized"
      ],
      "additionalProperties": false,
      "$id": "ItemSizeClassificationType"
    },
    "Weight": {
      "type": "object",
      "properties": {
        "value": {
          "type": "integer",
          "description": "Actual weight in [g].",
          "maxLength": 6
        },
        "scaleId": {
          "type": "string",
          "description": "The id of the scale (e.g. HAE-024)"
        },
        "state": {
          "$ref": "#/definitions/WeightMeasurementState",
          "description": "Weighing errors"
        }
      },
      "additionalProperties": false,
      "description": "Weight measurement of the mail piece.",
      "$id": "Weight"
    },
    "WeightMeasurementState": {
      "type": "object",
      "properties": {
        "isLegalForTrade": {
          "type": "boolean",
          "description": "False: Weight is not legal for trade."
        },
        "packageDistanceError": {
          "type": "boolean"
        },
        "packageLengthError": {
          "type": "boolean"
        },
        "externalError": {
          "type": "boolean"
        },
        "invalidMeasurement": {
          "type": "boolean"
        },
        "overweight": {
          "type": "boolean",
          "description": "Weight higher than max. weight."
        },
        "underweight": {
          "type": "boolean",
          "description": "Weight lower than min weight."
        },
        "overload": {
          "type": "boolean"
        },
        "underload": {
          "type": "boolean"
        },
        "conveyorSpeedChangedDuringMeasurement": {
          "type": "boolean"
        },
        "conveyorSpeedOutOfMaxLimit": {
          "type": "boolean"
        },
        "alibiStorageAtScaleFailed": {
          "type": "boolean"
        },
        "scaleDataFormatError": {
          "type": "boolean"
        }
      },
      "required": [
        "isLegalForTrade"
      ],
      "additionalProperties": false,
      "$id": "WeightMeasurementState"
    },
    "LegalForTrade": {
      "type": "object",
      "properties": {
        "actualVolume": {
          "type": "integer",
          "description": "# GER-TODO\r\n\r\nRealvolumen VMS#1 wenn VMS#1 = VMS420/520 Realvolumen = 000000 bei VMS#1 = VMS410/510\r\n[dm3]",
          "maxLength": 5
        },
        "boxVolume": {
          "type": "integer",
          "description": "Boxvolumen = Länge x Breite x Höhe\r\n[dm3]",
          "maxLength": 5
        },
        "volumeRatio": {
          "type": "integer",
          "description": "Realvolumen / Boxvolumen in % ganzzahlig"
        },
        "shape": {
          "$ref": "#/definitions/ShapeType",
          "description": "Die Paketform."
        },
        "state": {
          "$ref": "#/definitions/LegalForTradeState"
        }
      },
      "additionalProperties": false,
      "description": "Customs information",
      "$id": "LegalForTrade"
    },
    "ShapeType": {
      "type": "string",
      "enum": [
        "CUBIC",
        "IRREGULAR"
      ],
      "$id": "ShapeType"
    },
    "LegalForTradeState": {
      "type": "object",
      "properties": {
        "conveyorSpeedError": {
          "type": "boolean",
          "description": "Conveyor speed is out of tolerance."
        },
        "storageError": {
          "type": "boolean",
          "description": "Alibi storage error."
        },
        "dimensionError": {
          "type": "boolean",
          "description": "VMS data is not legal for trade."
        },
        "weightError": {
          "type": "boolean",
          "description": "Weight data not legal for trade."
        }
      },
      "required": [
        "conveyorSpeedError",
        "storageError",
        "dimensionError",
        "weightError"
      ],
      "additionalProperties": false,
      "description": "Detailed information on legal for trade relevant measurements.\r\n\r\n- If all flags are false, the measurements are legal for trade.\r\n- If only weightError is true, dimension measurement is legal for trade.\r\n- If only dimensionError is true, weight measurement is legal for trade.\r\n- Otherwise, measurements are not legal for trade.",
      "$id": "LegalForTradeState"
    },
    "BinOccupancyState": {
      "type": "object",
      "properties": {
        "emptyBinOccupied": {
          "type": "boolean"
        },
        "binMultipleItemOccupied": {
          "type": "boolean"
        },
        "frontOverlappingLimitExceeded": {
          "type": "boolean"
        },
        "backOverlappingLimitExceeded": {
          "type": "boolean"
        },
        "multipleItemsDetected": {
          "type": "boolean"
        },
        "conveyingAidDetected": {
          "type": "boolean"
        }
      },
      "required": [
        "emptyBinOccupied",
        "binMultipleItemOccupied",
        "frontOverlappingLimitExceeded",
        "backOverlappingLimitExceeded",
        "multipleItemsDetected",
        "conveyingAidDetected"
      ],
      "additionalProperties": false,
      "description": "Doppelbelegung / Leerschalen-kontrolle\r\nemptyBinOccupied: Belegte Leerschale\r\nbinMultipleItemOccupied: Doppelbelegung - Erkennung der Schalenbelegung von DWS\r\nfrontOverlappingLimitExceeded: Überstand vorne zu groß\r\nbackOverlappingLimitExceeded: Überstand hinten zu groß\r\nmultipleItemsDetected: >= 2 Objekt erkannt\r\nconveyingAidDetected: Förderhilfe erkannt",
      "$id": "BinOccupancyState"
    }
  }
}

=== TechSysApi/cen-mc-rc-dist/v3.1.0/samples/generated-SubmitMailpiece.json
{
  "mailpieceId": "985144905783954939",
  "timestamp": "1967-11-04T02:25:27.656Z",
  "sourceId": "VFP12",
  "idTag": "sunt ex consequat Excepteur eu",
  "mpAttr": {
    "type": "FLAT_BUNDLE",
    "preknowledge": {
      "barCodes": [{
        "status": "DETECTED_AND_RECOGNIZED",
        "type": "CODE_128",
        "value": "reprehenderit veniam laborum"
      }],
      "location": {
        "face": "TOP",
        "polygon": {
          "dot": [{
            "x": 10899484.643620744,
            "y": -19604632.76309356
          }]
        }
      },
      "dimension": {
        "length": -82604266,
        "width": 91567190,
        "height": -25320614,
        "state": {
          "measurementResult": "NOK",
          "measurementRange": "OUTSIDE",
          "itemSizeClassification": {
            "ok": true,
            "oversized": true,
            "undersized": true
          }
        }
      },
      "weight": {
        "value": 40922027,
        "state": {
          "isLegalForTrade": false,
          "packageDistanceError": false,
          "packageLengthError": true,
          "externalError": false,
          "invalidMeasurement": true,
          "overweight": false,
          "underweight": true,
          "overload": false,
          "underload": true,
          "conveyorSpeedChangedDuringMeasurement": false,
          "conveyorSpeedOutOfMaxLimit": true,
          "alibiStorageAtScaleFailed": true,
          "scaleDataFormatError": false
        }
      },
      "legalForTrade": {
        "actualVolume": -97823830,
        "boxVolume": -9564511,
        "volumeRatio": 88660848,
        "shape": "IRREGULAR",
        "state": {
          "conveyorSpeedError": true,
          "storageError": true,
          "dimensionError": true,
          "weightError": false
        }
      },
      "binOccupancy": {
        "emptyBinOccupied": true,
        "binMultipleItemOccupied": true,
        "frontOverlappingLimitExceeded": true,
        "backOverlappingLimitExceeded": true,
        "multipleItemsDetected": true,
        "conveyingAidDetected": true
      }
    }
  }
}
